clalancette/oz/action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,29 +1,41 @@
-name: Python package
+---
+name: Run CI checks
 
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+on: [pull_request]
 
 jobs:
-  build:
-
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        python-version: ["3.9", "3.10"]
+  unittests-fedora:
+    runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install six yapf
-    - name: Run test
-      run: |
-        python test/run_all.py
+      - name: Checkout the repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Install required packages
+        run: sudo apt-get install make flake8 pylint
+      # it's not in Ubuntu 22.04, was added in 23.04
+      - name: Install diff-cover from pip
+        run: pip install diff-cover
+      - name: Run the tests
+        run: sudo make container-unittests-fedora
+      - name: Run diff-cover
+        run: diff-cover coverage.xml  --compare-branch=origin/$GITHUB_BASE_REF --fail-under=90
+      - name: Run diff-quality (pylint)
+        # we want to run this regardless of whether previous lint steps failed
+        if: success() || failure()
+        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=pylint --fail-under=90
+      - name: Run diff-quality (flake8)
+        # we want to run this regardless of whether previous lint steps failed
+        if: success() || failure()
+        run: diff-quality --compare-branch=origin/$GITHUB_BASE_REF --violations=flake8 --fail-under=90
+  unittests-el7:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Install make
+        run: sudo apt-get install make
+      - name: Run the tests
+        run: sudo make container-unittests-el7
